apiVersion: rhpam.kiegroup.org/v1 
kind: KogitoBuild
metadata:
  name: tf-boycott-service-build
  namespace: v-sharp
spec:
  type: RemoteSource
  runtime: quarkus
  gitSource:
    uri: https://github.ibm.com/prkhamit/redhat_hackathon_bamoe.git
    contextDir: tf-boycott-service
    reference: main
  source:
    sourceSecret:
      name: bamoe-git      
  resources:
    limits:
      memory: "2Gi"
      cpu: "1"
  env:
    - name: QUARKUS_PROFILE
      value: openshift
